function [fitresult, gof] = createFit(groupavekeypressperblock)
%CREATEFIT(MEANCORRKEYPRESSPERSECNOOUTLIER)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: meanCorrKeyPressPerSecNoOutlier
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-Feb-2022 10:06:15


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( [], groupavekeypressperblock );
%[xData, yData] = prepareCurveData( [], meankeypressperblock );

% Set up fittype and options.
ft = fittype( 'a+(b/(1+exp(-c*x)))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.27985909374365 0.401774577740407 0.354988561809691];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 1 );
h = plot( fitresult, xData, yData);
%legend( h, 'Group average key presses per second', 'Model', 'Location', 'NorthEast', 'Interpreter', 'none', 'FontSize', 12 );
legend( h, 'Data', 'Model fit', 'Location', 'NorthEast', 'Interpreter', 'none', 'FontSize', 12 );
% Label axes
%ylabel( 'Key presses/ second', 'Interpreter', 'none','FontSize', 13  );
ylabel('Motor performance (keypress per second)','FontSize', 13  );
xlabel('Block', 'FontSize', 13);
%title('Group-level average skill', 'FontSize', 15);
grid off
box off

%saveas(figure(1),'Identify95%learning.tiff')
saveas(figure(1),'95%learning.tiff')



